
server:
  port: 8005
spring:
  application:
    name: guli-vod
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 102400MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #注册中心保存我的ip

logging:
  level:
    root: error
    com.guli.guli_vod: debug
  file:
    name: D:\temp\log\guli_vod.log